monitor=,preferred,auto,1

exec-once = hyprpaper
exec-once = waybar

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec-once = killall xdg-desktop-portal-hyprland
exec-once = killall xdg-desktop-portal-wlr
exec-once = killall xdg-desktop-portal

exec-once = /usr/lib/xdg-desktop-portal-hyprland &
exec-once = sleep 2 && /usr/lib/xdg-desktop-portal &

$terminal = kitty
$menu = fuzzel
$Mod = SUPER

env = GDK_BACKEND,wayland
env = QT_QPA_PLATFORM,wayland
env = TERMINAL,kitty
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QPA_PLATFORM,wayland;xcb

general {
	gaps_in = 2
	gaps_out = 2
	border_size = 1
	col.active_border = rgba(33ccffee)
	col.inactive_border = rgba(595959aa)
}

decoration {
	rounding = 10
	blur {
		enabled = true
	}
	active_opacity = 1.0
	inactive_opacity = 1.0
}

animations {
	enabled = true
	animation = workspaces, 1, 4, default, fade
}

misc {
	disable_splash_rendering = true
	force_default_wallpaper = 0
}

input {
	kb_layout = us,ru
	kb_options = grp:alt_shift_toggle
	repeat_rate = 25
	repeat_delay = 200
}

cursor {
	no_hardware_cursors = false
	use_cpu_buffer = true
}

bind = $Mod, RETURN, exec, $terminal
bind = $Mod Shift, RETURN, exec, [float; size 725 450; center] $terminal
bind = ALT, F4, killactive
bind = $Mod, Q, killactive
bind = $Mod, Escape, exit
bind = $Mod, Space, exec, $menu
bind = $Mod, V, togglefloating

bind = $Mod, left, movefocus, l
bind = $Mod, right, movefocus, r
bind = $Mod, up, movefocus, u
bind = $Mod, down, movefocus, d

bind = ALT, Tab, cyclenext
bind = ALT, Tab, bringactivetotop

bind = $Mod, 1, workspace, 1
bind = $Mod, 2, workspace, 2
bind = $Mod, 3, workspace, 3
bind = $Mod, 4, workspace, 4
bind = $Mod, 5, workspace, 5
bind = $Mod, 6, workspace, 6
bind = $Mod, 7, workspace, 7
bind = $Mod, 8, workspace, 8
bind = $Mod, 9, workspace, 9

bind = $Mod Shift, 1, movetoworkspace, 1
bind = $Mod Shift, 2, movetoworkspace, 2
bind = $Mod Shift, 3, movetoworkspace, 3
bind = $Mod Shift, 4, movetoworkspace, 4
bind = $Mod Shift, 5, movetoworkspace, 5
bind = $Mod Shift, 6, movetoworkspace, 6
bind = $Mod Shift, 7, movetoworkspace, 7
bind = $Mod Shift, 8, movetoworkspace, 8
bind = $Mod Shift, 9, movetoworkspace, 9

bindm = $Mod, mouse:272, movewindow
bindm = $Mod, mouse:273, resizewindow

binde = $Mod SHIFT, right, resizeactive, 40 0
binde = $Mod SHIFT, left, resizeactive, -40 0
binde = $Mod SHIFT, up, resizeactive, 0 -40
binde = $Mod SHIFT, down, resizeactive, 0 40

bind = $Mod CTRL, left, swapwindow, l
bind = $Mod CTRL, right, swapwindow, r
bind = $Mod CTRL, up, swapwindow, u
bind = $Mod CTRL, down, swapwindow, d

bind = $Mod SHIFT, Alt_L, movetoworkspacesilent, special:magic
bind = $Mod, Alt_L, togglespecialworkspace, magic

bind = , Print, exec, grim -g "$(slurp)" - | tee ~/$(date +'%Y%m%d_%H%M%S').png | wl-copy
bind = Shift, Print, exec, grim - | swappy -f -
